FROM ubuntu:20.04
RUN apt-get update

# IB/PSM Stack from https://github.com/TACC/tacc-containers/blob/master/containers/tacc-ubuntu18-mvapich2.3-psm2
RUN apt-get install -yq --no-install-recommends gfortran bison libibverbs-dev libnuma-dev \
    	libibmad-dev libibumad-dev librdmacm-dev libxml2-dev ca-certificates libfabric-dev

# Other utilities
RUN apt-get -y install curl g++ make

ARG PSM=PSM2
ARG PSMV=11.2.86
ARG PSMD=opa-psm2-${PSM}_${PSMV}

RUN curl -L https://github.com/intel/opa-psm2/archive/${PSM}_${PSMV}.tar.gz | tar -xzf - \
    && cd ${PSMD} \
    && make PSM_AVX=1 -j $(nproc --all 2>/dev/null || echo 2) \
    && make LIBDIR=/usr/lib/x86_64-linux-gnu install \
    && cd ../ && rm -rf ${PSMD}

# Install mvapich2-2.3 from https://github.com/TACC/tacc-containers/blob/master/containers/tacc-ubuntu18-mvapich2.3-psm2
ARG MAJV=2
ARG MINV=3
ARG BV=.1
ARG DIR=mvapich${MAJV}-${MAJV}.${MINV}${BV}

RUN curl http://mvapich.cse.ohio-state.edu/download/mvapich/mv${MAJV}/${DIR}.tar.gz | tar -xzf - \
    && cd ${DIR} \
    && ./configure \
	--with-device=ch3:psm \
	--with-ch3-rank-bits=32 \
	--enable-fortran=yes \
	--enable-cxx=yes \
	--enable-romio \
	--enable-fast=O3 \
    && make -j $(nproc --all 2>/dev/null || echo 2) \
    && make install \
    && cd ../ && rm -rf ${DIR} \
    && rm -rf /usr/local/share/doc/mvapich2

# PYOPATRA Requirements
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install libhdf5-dev \
    cmake \
    libeigen3-dev \
    pybind11-dev \
    python3 \
    libpython3-dev \
    python3-pip \
    python-is-python3 \
    && pip3 install numpy scipy matplotlib coverage pytest netcdf4 mpi4py h5py \
    && mkdir data

COPY . /PYOPATRA

RUN pip3 install PYOPATRA/ --install-option="--knl"
