name: HPC-Tests

on:
    push:
        branches: [ hpc-tests ]
        paths-ignore:
          - 'docs/**'
          - 'examples/**'
          - 'README.rst'
          - 'LICENSE.txt'

    workflow_dispatch:

jobs:
    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Step 1
              run: ls $GITHUB_WORKSPACE

